[[req_mlt_content]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mlt/content*
^|A |Every 200-response of the server with the media type application/vnd.maplibre-vector-tile SHALL be a MapLibre Vector Tile document representing only one tile.
^|B |A feature SHALL contain a geometry field. A feature SHALL contain a type field as described in the Geometry Types section.
^|C |The grid space for the MLT coordinates SHALL map linearly to the coordinates in the tile extent expressed in the Tileset CRS unless a _prior arrangement_ applies to use an alternative CRS; and in this case the linear mapping SHALL be done to the alternative CRS and not with the Tileset CRS. For example, an extension could negotiate another CRS for coordinates with a query parameter. In particular the 0,0 coordinate in the MLT maps to the top-left corner of the tile. The bottom-right corner of the tile corresponds the bottom-right corner of the MLT grid.
|===
////

[requirement]
====
[%metadata]
identifier:: /req/mlt/content
part:: Every 200-response of the server with the media type application/vnd.maplibre-vector-tile SHALL be a MapLibre Vector Tile document representing only one tile.
part:: A feature SHALL contain a geometry field. A feature SHALL contain a type field as described in the Geometry Types section.
part:: The grid space for the MLT coordinates SHALL map linearly to the coordinates in the tile extent expressed in the Tileset CRS unless a _prior arrangement_ applies to use an alternative CRS; and in this case the linear mapping SHALL be done to the alternative CRS and not with the Tileset CRS. For example, an extension could negotiate another CRS for coordinates with a query parameter. In particular the 0,0 coordinate in the MLT maps to the top-left corner of the tile. The bottom-right corner of the tile corresponds the bottom-right corner of the MLT grid.
====
